<a href="https://colab.research.google.com/github/cqqqj/shen-du-xue-xi/blob/main/%E2%80%9C02_NumPy%E2%80%9D%E7%9A%84%E5%89%AF%E6%9C%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

<img src="https://raw.githubusercontent.com/LisonEvf/practicalAI-cn/master/images/logo.png" width=150>

在本课中，我们将学习使用NumPy包进行数值分析的基础知识。

<img src="https://raw.githubusercontent.com/LisonEvf/practicalAI-cn/master/images/numpy.png" width=300>




# NumPy 基础知识

In [1]:
import numpy as np

In [2]:
# 使得多次生成的随机数相同
np.random.seed(seed=1234)

In [3]:
# 标量（scalars）
x = np.array(6) # scalar
print ("x: ", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:  6
x ndim:  0
x shape: ()
x size:  1
x dtype:  int64


In [4]:
# 一维数组（array）
x = np.array([1.3 , 2.2 , 1.7])
print ("x: ", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print ("x dtype: ", x.dtype) # notice the float datatype

x:  [1.3 2.2 1.7]
x ndim:  1
x shape: (3,)
x size:  3
x dtype:  float64


In [5]:
# 三维数组（矩阵（matrix））
x = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print ("x:\n", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
x ndim:  3
x shape: (1, 3, 3)
x size:  9
x dtype:  int64


In [6]:
# 函数
print ("np.zeros((2,2)):\n", np.zeros((2,2)))
print ("np.ones((2,2)):\n", np.ones((2,2)))
print ("np.eye((2)):\n", np.eye((2)))
print ("np.random.random((2,2)):\n", np.random.random((2,2)))

np.zeros((2,2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.eye((2)):
 [[1. 0.]
 [0. 1.]]
np.random.random((2,2)):
 [[0.19151945 0.62210877]
 [0.43772774 0.78535858]]


# 索引

In [7]:
# 索引（indexing）
x = np.array([1, 2, 3])
print ("x[0]: ", x[0])
x[0] = 0
print ("x: ", x)

x[0]:  1
x:  [0 2 3]


In [11]:
# 切片（slicing）
x = np.array([[1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]])
print (x)
print ("x column 1: ", x[:, 1])#有一个索引，降低维度从2维变1维
print ("x row 0: ", x[0, :])
a=x[:3, 1:3]#a是二维的正常 a[0,1]索引
print ("x rows 0,1,2 & cols 1,2: \n",a)#都切片，保持维度 wei1
a[0,0]=0#这是a的行索引
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column 1:  [ 2  6 10]
x row 0:  [1 2 3 4]
x rows 0,1,2 & cols 1,2: 
 [[ 2  3]
 [ 6  7]
 [10 11]]
[[ 1  0  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
x = np.array([[1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]])

In [13]:
# 整数数组索引
print (x)#len(x)返回列表中的元素个数
rows_to_get = np.arange(len(x))#返回外层列表的长度【二维数组列表里有列表，内部列表的个数才是len
print ("rows_to_get: ", rows_to_get)
cols_to_get = np.array([0, 2, 1])
print ("cols_to_get: ", cols_to_get)
print ("indexed values: ", x[rows_to_get, cols_to_get])
#花式索引x[[0,1,2],[0,2,1]]  索引降低维度 得到的是1维数组【】

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
rows_to_get:  [0 1 2]
cols_to_get:  [0 2 1]
indexed values:  [ 1  7 10]


In [ ]:
# 布尔数组索引
x = np.array([[1,2], [3, 4], [5, 6]])
print ("x:\n", x)
print ("x > 2:\n", x > 2)#返回布尔值
print ("x[x > 2]:\n", x[x > 2])#索引依旧降低维度

x:
 [[1 2]
 [3 4]
 [5 6]]
x > 2:
 [[False False]
 [ True  True]
 [ True  True]]
x[x > 2]:
 [3 4 5 6]


# 数组基础知识

In [15]:
# 数学基础
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[1,2], [3,4]], dtype=np.float64)
print ("x + y:\n", np.add(x, y)) # or x + y
print ("x - y:\n", np.subtract(x, y)) # or x - y
print ("x * y:\n", np.multiply(x, y)) # or x * y
#区分于x@y(np.dot(x,y))【矩阵乘法】 x*y是逐个相乘（将两个矩阵中对应位置的元素相乘，结果矩阵的形状与原矩阵相同）

x + y:
 [[2. 4.]
 [6. 8.]]
x - y:
 [[0. 0.]
 [0. 0.]]
x * y:
 [[ 1.  4.]
 [ 9. 16.]]


<img src="https://raw.githubusercontent.com/LisonEvf/practicalAI-cn/master/images/matrix.png" width=400>


In [14]:
# 点积（向量于矩阵乘法）
a = np.array([[1,2,3], [4,5,6]], dtype=np.float64) # 我们可以指定dtype
b = np.array([[7,8], [9,10], [11, 12]], dtype=np.float64)
print (a.dot(b))

[[ 58.  64.]
 [139. 154.]]


In [16]:
# 跨维度求和（跨维度就降低维度）
x = np.array([[1,2],[3,4]])
print (x)
print ("sum all: ", np.sum(x)) # 将所有元素相加
print ("sum by col: ", np.sum(x, axis=0)) # 逐列将元素相加
print ("sum by row: ", np.sum(x, axis=1)) # 逐行将元素相加

[[1 2]
 [3 4]]
sum all:  10
sum by col:  [4 6]
sum by row:  [3 7]


In [17]:
# 转置
print ("x:\n", x)
print ("x.T:\n", x.T)

x:
 [[1 2]
 [3 4]]
x.T:
 [[1 3]
 [2 4]]


# 数组高级知识

In [19]:
# np.tile：重复维度
x = np.array([[1,2], [3,4]])#len(x)值为2
y = np.array([5, 6])
addent = np.tile(y, (len(x), 1))
print ("y: \n", y)
print ("addent: \n", addent)
z = x + addent
print ("z:\n", z)
"""
len(x) 是数组 x 的行数，这里是 2，表示在垂直方向（行）上重复 2 次。
1 表示在水平方向（列）上不重复
所以y变化后
[[5, 6],
 [5, 6]]
"""

addent: 
 [5 6]
addent: 
 [[5 6]
 [5 6]]
z:
 [[ 6  8]
 [ 8 10]]


'\nlen(x) 是数组 x 的行数，这里是 2，表示在垂直方向（行）上重复 2 次。\n1 表示在水平方向（列）上不重复\n所以y变化后\n[[5, 6],\n [5, 6]]\n'

In [20]:
# 广播（broadcasting）#维度至少为1且两个元组至少再一个维度上相同
x = np.array([[1,2], [3,4]])
y = np.array([5, 6])
z = x + y
print ("z:\n", z)

z:
 [[ 6  8]
 [ 8 10]]


In [21]:
# 改变维度
x = np.array([[1,2], [3,4], [5,6]])
print (x)
print ("x.shape: ", x.shape)
y = np.reshape(x, (2, 3))
print ("y.shape: ", y.shape)
print ("y: \n", y)

[[1 2]
 [3 4]
 [5 6]]
x.shape:  (3, 2)
y.shape:  (2, 3)
y: 
 [[1 2 3]
 [4 5 6]]


numpy.squeeze(a, axis=None)
1 删除指定大小的维度

```
# 此内容为代码格式
当x.shape为(3, 1, 4)时
使用 np.squeeze(x, 1) 删除第1轴（即中间的维度）：\

```
2. 移除所有单维度
如果不指定 axis 参数，np.squeeze 会移除所有大小为1的维度：

```
x = np.array([[[1, 2, 3, 4]]])  # 形状为 (1, 1, 4)

y = np.squeeze(x)  # 默认移除所有单维度

print("压缩后的数组 y 的形状:", y.shape)  # 输出: (4,)
print(y)  # 输出: [1 2 3 4]


```
3. 指定多个轴进行压缩（axis=0，前提该轴大小为1）
可以同时指定多个轴进行压缩，前提是这些轴的大小都为1：


```
x = np.array([[[1], [2], [3]]])  # 形状为 (1, 3, 1)

y = np.squeeze(x, axis=(0, 2))  # 移除第0轴和第2轴

print("压缩后的数组 y 的形状:", y.shape)  # 输出: (3,)
print(y)  # 输出: [1 2 3]









In [22]:
# 删除维度（重点）
x = np.array([[[1,2,1]],[[2,2,3]]])
print ("x.shape: ", x.shape)
y = np.squeeze(x, 1) # 删除维度1（用于从数组 x 中移除指定轴（维度）上大小为1的维度）
print ("y.shape: ", y.shape)
print ("y: \n", y)
#因为行维度的大小为1，所以删除行维度

x.shape:  (2, 1, 3)
y.shape:  (2, 3)
y: 
 [[1 2 1]
 [2 2 3]]


拓展维度
numpy.expand_dims(a, axis)

​a: 要扩展维度的数组。
​axis: 新维度插入的位置。可以是整数，表示在哪个轴之前插入新维度。
返回值

返回一个新的数组，该数组在指定的轴上增加了一个大小为1的维度。原始数组不会被修改。
y = np.expand_dims(x, 1)

就是在第一轴上增加大小为1的维度 np.shape(x)从（2，3）变为（2，1，3）

In [ ]:
# 添加维度
x = np.array([[1,2,1],[2,2,3]])
print ("x.shape: ", x.shape)
y = np.expand_dims(x, 1) # 扩展维度1
print ("y.shape: ", y.shape)
print ("y: \n", y)

x.shape:  (2, 3)
y.shape:  (2, 1, 3)
y: 
 [[[1 2 1]]

 [[2 2 3]]]


# 其它资源

你不必熟悉本文中任何东西，因为我们将在后面的课程中仔细研究NumPy。如果你对Numpy感到好奇，可以自行查看 [NumPy reference manual](https://docs.scipy.org/doc/numpy-1.15.1/reference/).